INPUT_SIZE:
- 224
- 224
backbone:
- - 1
  - Conv
  - - 64
    - 3
    - 2
    - null
    - 1
    - Hardswish
- - 5
  - InvertedResidualv2
  - - 32
    - 2
    - 1
- - 3
  - InvertedResidualv2
  - - 24
    - 6
    - 2
- - 1
  - Conv
  - - 352
    - 3
    - 2
    - null
    - 1
    - ReLU
- - 4
  - InvertedResidualv3
  - - 3
    - 4.4
    - 8
    - 0
    - 1
    - 2
- - 1
  - Conv
  - - 768
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - FixedConv
  - - 6
    - 1
    - 1
    - null
    - 1
    - null
depth_multiple: 0.75
input_channel: 3
width_multiple: 0.75
