INPUT_SIZE:
- 224
- 224
input_channel: 3

depth_multiple: 0.75
width_multiple: 0.5

backbone:
  [
    [3, 'Conv', [16, 3, 1, null, 1, 'Hardswish']], #1
    # [3, 'Conv', [48, 5, 2, null, 1, 'ReLU']], #2
    [3, 'DWConv', [48, 5, 2, null, 'ReLU']], #2
    [3, 'InvertedResidualv2', [64, 7, 2]], #3
    [3, 'InvertedResidualv2', [128, 3, 1]], #4
    # [3, 'Conv', [320, 3, 1, null, 1, 'ReLU']], #5
    [2, 'DWConv', [256, 5, 2, null, 'Hardswish']], #6
    [1, 'Conv', [384, 1, 1]],
    [1, 'GlobalAvgPool', []],
    [1, 'FixedConv', [6, 1, 1, null, 1, null]],
  ]
