input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
  [
    # [repeat, module, args]
    [1, Conv, [32, 3, 2]],
    # [repeat, MBConv: t, c, s, k]
    [2, MBConv, [1, 16, 1, 3]],
    [2, MBConv, [6, 24, 2, 3]],
    [2, MBConv, [6, 40, 2, 5]],
    [3, MBConv, [6, 80, 2, 3]],
    [3, MBConv, [6, 112, 1, 5]],
    [4, MBConv, [6, 192, 2, 5]],
    [1, MBConv, [6, 320, 1, 3]],
    [1, Conv, [1280, 1, 1]],
    [1, GlobalAvgPool, []],
    [1, Conv, [6, 1, 1, null, 1, null]]

  ]